### ISSUE TITLE
Error "g_form is not defined" in ATF test

### ISSUE THREAD

**Issue by NagyBandi** [platform-experience/pi-multiform#1]
We are using Multiform successfully (big thanks!), but when we try to write an ATF test, the Open a Form (SP) step throws a "FAILURE: g_form is not defined. A valid form must have g_form defined" error.
The page seems to load fine in (and out of) the runner, there are no error messages displayed, client scripts using g_form run without an issue.

We are on New York Patch 2, but the issue is the same on Madrid, too.

**Comment by dylanlindgren** [comment]
Hi Nagy, unfortunately this widget is not built to work with ATF form testing. It is perhaps something I can investigate whether it is possible, but it is not designed and will not work with it at the moment.

**Comment by rajiyash3004** [comment]
Solution for this plz??
